### ISSUE TITLE
Tests fail when using Test::APIcast >= 0.18

### ISSUE THREAD

**Issue by davidor** [3scale/apicast-cloud-hosted#13]
See this PR for example: #12 
I tried several versions of `Test::APIcast` and found that tests fail with 0.18 and 0.19 (latest release).

**Comment by davidor** [comment]
It's because of this change: https://github.com/3scale/Test-APIcast/pull/15/files#diff-70e52a05439c193ca5d6b5a2f89f6b2aR161

The `production` environment is added always, but it is not defined in this project.

@mikz I can't remember why `production` is added by default. Do you remember the problem that was solved with that?

**Comment by mikz** [comment]
Guess we should define production environment then...

That PR allows loading multiple environment configurations. For example standalone + production. The same it can be done from a CLI.
